"""E-FLOOD, satellites first (owner 2026-10-06: "show flood area … for each reservoir discharge release scenario"; "The
satellite images might be unreliable, please validate before use. You can also compare with google or any global flood
info or portal"; "Flood area generated by DEM is firstly for experiment").
Finding that frames this: in three years of records (2023-09 … 2026-10) none of the five Phetchaburi gauges went over its
bank (research/2026-10-06 events check) — so no recent release-driven flood exists to validate against. The one in reach:
August 2018, when Kaeng Krachan released up to 24.36 ล้าน ลบ.ม./วัน (21 Aug; the largest since).
Copernicus GFM (keyless STAC, archive from 2015-01-01; Sentinel-1, 20 m; ensemble of three algorithms; exclusion mask =
where radar cannot see floods; reference water = permanent/seasonal water): every pass over the lowland below the dam
(lon 99.45–100.10, lat 12.75–13.30) for (a) 2018-07-15 … 2018-10-15 and (b) 2026-09-01 … today, on one 0.0002° grid.
Per pass: valid share, excluded share, flooded km² outside reference water. 2018: consistency between consecutive passes;
the August–September extent (flooded in ≥ 2 passes, so one-pass speckle does not count). Now: GFM against ONWR/GISTDA's
observed flooded polygons in the same box (onwr_flood_kaeng_krachan, flood-area-poly) — agreement where GFM could see.
Outputs (scratch, not the repo): /out/gfm_2018_mask.npz, a JSON summary on stdout.
Run (host, research libraries in a scratch folder): PYTHONPATH=$PYLIB python3 research/2026-10-06_flood_satellite_kk.py OUT_DIR"""
import json, sys, time, datetime as dt, urllib.request
import numpy as np
import rasterio
from rasterio.transform import from_origin
from rasterio.warp import reproject, transform_bounds
from rasterio.enums import Resampling

UA = "BKK-FloodWatch/0.2 (+https://flood.autobahn.bot)"
OUT = sys.argv[1]
W, S_, E, N = 99.45, 12.75, 100.10, 13.30
RES = 0.0002
NX, NY = int(round((E - W) / RES)), int(round((N - S_) / RES))
DST_T = from_origin(W, N, RES, RES)
PIX_KM2 = (RES * 111.32) * (RES * 111.32 * np.cos(np.radians((S_ + N) / 2)))


def get(url):
    for k in range(4):
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA}), timeout=120) as r:
                return json.loads(r.read())
        except Exception:
            if k == 3:
                raise
            time.sleep(5 * (k + 1))


def items(dt_range):
    url = f"https://stac.eodc.eu/api/v1/collections/GFM/items?bbox={W},{S_},{E},{N}&datetime={dt_range}&limit=100"
    out = []
    while url:
        d = get(url)
        out += d.get("features", [])
        url = next((l["href"] for l in d.get("links", []) if l.get("rel") == "next"), None)
    return out


def read(href):
    with rasterio.open(href) as r:
        b = transform_bounds("EPSG:4326", r.crs, W, S_, E, N)
        win = rasterio.windows.from_bounds(*b, r.transform).round_offsets().round_lengths()
        win = win.intersection(rasterio.windows.Window(0, 0, r.width, r.height))
        src = r.read(1, window=win)
        dst = np.full((NY, NX), 255, np.uint8)
        reproject(src, dst, src_transform=r.window_transform(win), src_crs=r.crs, src_nodata=255, dst_transform=DST_T,
                  dst_crs="EPSG:4326", dst_nodata=255, resampling=Resampling.nearest)
        return dst


def passes(dt_range):
    rows = []
    for it in sorted(items(dt_range), key=lambda x: x["properties"]["datetime"]):
        a = it["assets"]
        if "ensemble_flood_extent" not in a:
            continue
        try:
            fl = read(a["ensemble_flood_extent"]["href"])
            if (fl != 255).mean() < 0.05:
                continue  # the item's bbox is wider than its strip: nothing imaged here
            ex = read(a["exclusion_mask"]["href"]) if "exclusion_mask" in a else np.zeros_like(fl)
            rw = read(a["reference_water_mask"]["href"]) if "reference_water_mask" in a else np.zeros_like(fl)
        except Exception as e:
            print("skip", it["id"], type(e).__name__, str(e)[:80], flush=True)
            continue
        valid = (fl != 255)
        flood = valid & (fl == 1) & (rw != 1) & (ex != 1)
        rows.append({"t": it["properties"]["datetime"], "id": it["id"], "valid": float(valid.mean()), "excluded": float(((ex == 1) & valid).mean()),
                     "flood_km2": float(flood.sum() * PIX_KM2), "flood": flood, "valid_mask": valid & (ex != 1), "refwater": (rw == 1)})
        print(f"{rows[-1]['t'][:16]} valid {rows[-1]['valid']:.2f} excluded {rows[-1]['excluded']:.2f} flooded {rows[-1]['flood_km2']:.1f} km²", flush=True)
    return rows


summary = {}
print("=== 2018 (Kaeng Krachan's largest releases since: up to 24.36 ล้าน ลบ.ม./วัน on 21 Aug)", flush=True)
p18 = passes("2018-07-15T00:00:00Z/2018-10-15T00:00:00Z")
# consistency: consecutive passes — of the land both could see, how much of one's flood the next also maps
cons = []
for a, b in zip(p18, p18[1:]):
    both = a["valid_mask"] & b["valid_mask"]
    fa, fb = a["flood"] & both, b["flood"] & both
    if fa.sum() > 500:
        cons.append({"from": a["t"][:10], "to": b["t"][:10], "kept": float((fa & fb).sum() / fa.sum())})
summary["2018_passes"] = [{k: v for k, v in r.items() if k in ("t", "valid", "excluded", "flood_km2")} for r in p18]
summary["2018_consistency"] = cons
win = [r for r in p18 if "2018-08-10" <= r["t"][:10] <= "2018-09-20"]
if win:
    count = np.sum([r["flood"] for r in win], axis=0)
    seen = np.sum([r["valid_mask"] for r in win], axis=0)
    mask2 = count >= 2
    summary["2018_extent_km2_two_passes"] = float(mask2.sum() * PIX_KM2)
    summary["2018_extent_km2_any_pass"] = float((count >= 1).sum() * PIX_KM2)
    np.savez_compressed(f"{OUT}/gfm_2018_mask.npz", count=count.astype(np.uint8), seen=seen.astype(np.uint8),
                        refwater=np.any([r["refwater"] for r in win], axis=0), bounds=np.array([W, S_, E, N]), res=RES)
print("=== now (2026-09-01 … today) and ONWR/GISTDA's observed flooded area", flush=True)
p26 = passes("2026-09-01T00:00:00Z/2026-10-07T00:00:00Z")
summary["2026_passes"] = [{k: v for k, v in r.items() if k in ("t", "valid", "excluded", "flood_km2")} for r in p26]
try:
    onwr = json.load(open(f"{OUT}/onwr_flood_kk.json"))  # exported from the database state before this run
    from rasterio.features import rasterize
    shapes = [({"type": "Polygon", "coordinates": [[[lon, lat] for lat, lon in ring] for ring in f["rings"]]}, 1)
              for f in onwr["layers"]["flood-area-poly"]["features"]]
    om = rasterize(shapes, out_shape=(NY, NX), transform=DST_T, fill=0, dtype=np.uint8).astype(bool) if shapes else np.zeros((NY, NX), bool)
    if p26:
        gf = np.any([r["flood"] for r in p26], axis=0); gv = np.any([r["valid_mask"] for r in p26], axis=0)
        summary["onwr_vs_gfm"] = {"onwr_km2": float(om.sum() * PIX_KM2), "onwr_seen_by_gfm_share": float((om & gv).sum() / max(om.sum(), 1)),
                                  "onwr_area_gfm_flooded_share": float((om & gv & gf).sum() / max((om & gv).sum(), 1)),
                                  "gfm_flood_km2": float(gf.sum() * PIX_KM2), "gfm_flood_in_onwr_share": float((gf & om).sum() / max(gf.sum(), 1))}
except FileNotFoundError:
    summary["onwr_vs_gfm"] = "no ONWR export"
print("SUMMARY_JSON", json.dumps(summary))
